# Generated by Django 5.2.7 on 2025-10-16 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('login', models.CharField(db_column='Login', max_length=50, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('dt_inclusao', models.DateTimeField(db_column='DtInclusao', default=django.utils.timezone.now)),
                ('dt_alteracao', models.DateTimeField(auto_now=True, db_column='DtAlteracao')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_admin', models.BooleanField(db_column='IsAdmin', default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
            },
        ),
    ]
