# Generated by Django 5.2.7 on 2025-10-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('id_tipo_pokemon', models.AutoField(db_column='IDTipoPokemon', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pokémon',
                'verbose_name_plural': 'Tipos de Pokémon',
                'db_table': 'TipoPokemon',
            },
        ),
        migrations.CreateModel(
            name='PokemonUsuario',
            fields=[
                ('id_pokemon_usuario', models.AutoField(db_column='IDPokemonUsuario', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('imagem_url', models.CharField(db_column='ImagemUrl', max_length=255)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('grupo_batalha', models.BooleanField(db_column='GrupoBatalha', default=False)),
                ('favorito', models.BooleanField(db_column='Favorito', default=False)),
                ('id_usuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
                ('id_tipo_pokemon', models.ForeignKey(db_column='IDTipoPokemon', on_delete=django.db.models.deletion.PROTECT, related_name='pokemons', to='pokemon.tipopokemon')),
            ],
            options={
                'verbose_name': 'Pokémon do Usuário',
                'verbose_name_plural': 'Pokémons dos Usuários',
                'db_table': 'PokemonUsuario',
                'unique_together': {('id_usuario', 'codigo')},
            },
        ),
    ]
